spring.application.name=Api-Recibos
# Configuracao do Banco de Dados H2 (Em memoria)
spring.datasource.url=jdbc:h2:file:./Banco_de_dados/recibosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Table.Recibos
spring.datasource.password=0405
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Permite criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
# Mostra o SQL no terminal (opcional, bom para ver a magia a acontecer)
spring.jpa.show-sql=true
# para ativar o bd
spring.h2.console.enabled=true
# banco de dados h2
Acesso.H2=http://localhost:8080/h2-console
spring.h2.console.settings.web-allow-others=true
