spring.application.name=Api-Recibos
# MongoDB Configuration
spring.data.mongodb.uri=${DATABASE_URL}
spring.data.mongodb.database=lista_de_pdf
spring.data.mongodb.auto-index-creation=true

## rodar docker ##
# .\mvnw clean package -DskipTests
# docker build -t minha-api-recibos .
# docker run -p 8080:8080 -v "C:\Users\Usuario\Desktop\Software NF-E\Api-NF-E\Banco_de_dados:/app/Banco_de_dados" minha-api-recibos

    